add report routers
avantifellows/reporting pull request #19
Opened 2022-12-21 11:42 UTC by ShekharGaikwadDS

2022-12-21 12:25 UTC, pritamps requested changes

2022-12-21 12:25 UTC, pritamps commented on app/db/student_quiz_reports_db.py
> +                    KeyConditionExpression=Key("session_id").eq(session_id)
This query is getting the reports for all students in the session, right?

If so, why is it in the method `get_students_quiz_report`? This method (as the name suggests) should get the report for the quiz for one student

2022-12-21 12:25 UTC, pritamps commented on app/models/student_quiz_report.py
> +                session_id=session_id, user_id=""
Shouldn't the passed `user_id` be `None` since that's what the `if` condition is checking?

2022-12-21 12:25 UTC, pritamps commented on app/routers/reports.py
> +        @api_router.get("/student_quiz_report/{session_id}")
This shouldn't be `student_quiz_report` here, since it's not for a combination of student and quiz. It should just be `quiz_report`

2022-12-21 17:34 UTC, ShekharGaikwadDS commented on app/db/student_quiz_reports_db.py
> +                    KeyConditionExpression=Key("session_id").eq(session_id)
get_student_quiz_report method is currently set up to return all student quiz reports for a given session rather than just one student's report. cause the KeyConditionExpression in the query call does not include a condition to filter the results based on the user_id field.
I can rename the method to get_all_student_quiz_reports to better reflect its current behavior and can create a new method called get_student_quiz_report that retrieves a single student's quiz report based on their user_id and session_id

2022-12-21 17:37 UTC, ShekharGaikwadDS commented on app/models/student_quiz_report.py
> +                session_id=session_id, user_id=""
Yes, you are correct that the user_id argument in the get_student_quiz_report method should default to None to match the behavior of the method I'll update it

2022-12-21 17:41 UTC, ShekharGaikwadDS commented on app/routers/reports.py
> +        @api_router.get("/student_quiz_report/{session_id}")
You are correct that the name of the student_quiz_report endpoint is somewhat misleading,
I'll update with more appropriate name for this endpoint might be quiz_report_for_student or quiz_report

2023-01-04 08:35 UTC, pritamps commented on app/db/student_quiz_reports_db.py
> +                    KeyConditionExpression=Key("session_id").eq(session_id)
So, here is the nomenclature I am thinking:

`get_student_quiz_report` - gets report for one student for one quiz

So, in your case, since you are getting all the reports for a given quiz, you can have a *separate* method called `get_quiz_report`, since what you are doing here is getting all the student reports for a single quiz. Does that make sense?

2023-01-04 08:39 UTC, pritamps requested changes

2023-01-04 08:39 UTC, pritamps commented on app/models/student_quiz_report.py
> +    def get_student_quiz_report_by_session_id(self, session_id: str) -> List[dict]:
This method is not being used anywhere? Maybe you can remove it?

2023-01-04 08:39 UTC, pritamps commented on app/routers/reports.py
> +        @api_router.get("/quiz_report_by_session_id/{session_id}")
The route should just be `/quiz_report/{session_id}`

2023-01-13 07:11 UTC, suryabulusu commented on app/db/student_quiz_reports_db.py
> +    def get_report_by_session_id(self, session_id):
why is this function used twice? same thing is there on Line 14?

2023-01-13 07:13 UTC, suryabulusu commented on app/models/student_quiz_report.py
> +from typing import List
why import this if you haven't used it anywhere?

2023-01-13 07:14 UTC, suryabulusu commented on app/routers/reports.py
> +            template = "quiz_report_by_session_id.html"
why have this variable `template`? You are not using it.

2023-01-13 16:52 UTC, suryabulusu commented on app/routers/reports.py
> +        def quiz_report_by_session_id(request: Request, session_id: str):
def `quiz_report:` is fine

2023-01-13 16:53 UTC, suryabulusu commented on app/routers/reports.py
> +                    status_code=400, detail="No student_quiz_report found"
No quiz_report found

2023-01-13 17:38 UTC, suryabulusu approved these changes
looks good -- can improve template with more data in next PR

2023-04-06 09:22 UTC, closed without merging