Initializes CI CD setup
avantifellows/reporting pull request #4
Opened 2022-08-25 13:16 UTC by suryabulusu

- Adds `prod.yaml` and `staging.yaml` templates for lambda function initialization
- Adds github workflows for staging and production (via aws sam deploy)
- Adds `Mangum` adapter in `main.py` so that handler can run via lambda function

(already added secrets for each environment -- as of now, they are the same)

2022-08-30 05:11 UTC, deepansh96 requested changes

2022-08-30 05:11 UTC, deepansh96 commented on app/main.py
> +    "http://localhost:5050",
is this origin correct?
As far as I understand, this origins array means which URLs will be querying this backend right?
In quiz, we had the local, staging and prod URLs of the frontend
In this case, it's essentially this backend is querying itself right?

2022-08-30 05:11 UTC, deepansh96 commented on app/main.py
> +    "https://reporting.avantifellows.org",
why `report` in staging and `reporting` in prod?
any issue in keeping the names same?

2022-08-30 05:11 UTC, deepansh96 commented on requirements.txt
> +mangum==0.14.1
how is this `requirements.txt` file different than the one inside `app/` directory?

2022-09-01 04:44 UTC, suryabulusu commented on .github/workflows/deploy_to_prod.yml
> +          aws-region: us-east-1
i suppose the main aws AF account is created with `us-east-1` ? 🤔

2022-09-01 04:49 UTC, suryabulusu commented on README.md
> +
oh looks like i didn't commit the changes -- added in new commit

2022-09-01 05:14 UTC, suryabulusu commented on requirements.txt
> +mangum==0.14.1
its the same 🤔 mangum didn't exist before so i added here in `requirements.txt`. 
Then I copied this file to `app/` directory (wasn't there before) -- copied because its required for installations at lambda function end i suppose

2022-09-01 06:08 UTC, suryabulusu commented on app/internal/db.py
> +# checking only for secret key as of now
added others too

2022-09-01 06:09 UTC, suryabulusu commented on app/main.py
> +    "http://localhost:5050",
yup you are right -- removing it

2022-09-01 06:10 UTC, suryabulusu commented on app/main.py
> +    "https://reporting.avantifellows.org",
`reports-staging.avantifellows.org` ; `reports.avantifellows.org` -- i think this will be fine. pritam also preferred this. Quiz me bhi we had similar; `quiz-staging` and `quiz`

2022-09-05 05:17 UTC, deepansh96 commented on .github/workflows/deploy_to_prod.yml
> +          aws-region: us-east-1
no no there's no such thing as the main account being created with a region I suppose
Can you change it to ap south 1?

2022-09-05 05:21 UTC, deepansh96 requested changes

2022-09-05 05:21 UTC, deepansh96 commented on .github/workflows/deploy_to_staging.yml
> +        run: sam deploy --stack-name ReportingStaging --s3-bucket reporting-engine-staging --no-confirm-changeset --no-fail-on-empty-changeset --region ap-south-1 --capabilities CAPABILITY_IAM --para
You forgot to use that block separator (`>`) here :p

2022-09-05 05:21 UTC, deepansh96 commented on .github/workflows/deploy_to_staging.yml
> +          aws-region: us-east-1
ap-south-1

2022-09-05 05:21 UTC, deepansh96 commented on requirements.txt
> +mangum==0.14.1
My doubt was that why do we need 2 `requirements.txt`?
There should only be one no?
And if yes, then where should that exist?
I guess inside the `app` folder?

2022-09-06 07:44 UTC, merged